#spring.application.name=attendance
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/attendance?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rlarudrb119!

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    hibernate:
      ddl-auto: create